project_name: bi-zoom-demo
repomix_options:
  ignore:
    customPatterns:
    - node_modules
    - .git
    - .venv
  output:
    filePath: projects/bi-zoom-demo/outputs/repomix-output.md
    style: markdown
source: git@repo.dpsk12.org:amazon-web-services/machine-learning/student-risk-profile-reference-slim.git
